stages:
  - setup_tests
  - run_tests
  - pages
  - automated-api-tests

setup_and_run_tests:
  stage: setup_tests
  image: mcr.microsoft.com/playwright/python:v1.38.0-jammy
  script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - cp .env.example .env
    - python test_dotenv.py
    - PLAYWRIGHT_BROWSERS_PATH=/ms-playwright python -m playwright install --with-deps chromium
    - pytest --junitxml=reports/xml/report.xml --template=html1/index.html --report=reports/html/index.html -m ui -v
  artifacts:
    paths:
      - reports
    expire_in: 7 days  # Store artifacts for a week
    when: always
  cache:
    paths:
      - .cache/pip  # Cache pip dependencies
      - /ms-playwright  # Cache Playwright browsers
  variables:
    CI: "true"

pages:
  stage: pages
  script:
    - ls -la
    - ls -la reports/html
    - mkdir -p public
    - cp -r reports/html/* public/
  dependencies:
    - setup_and_run_tests
  artifacts:
    paths:
      - public
    expire_in: 7 days
  only:
    - main  # Deploy only on the main branch
