stages:
  - test
  - pages

tests:
  stage: test
  image: mcr.microsoft.com/playwright/python:v1.38.0-jammy
  script:
    - pip install -r requirements.txt
    - pytest --junitxml=reports/report.xml --template=html1/index.html --report=reports-html/report.html --base-url https://demoqa.com
  artifacts:
    paths:
      - reports/
      - reports-html/
pages:
  script:
    — mkdir .public
    — cp -r reports-html/* .public
    — mv .public public
  artifacts:
    paths:
      - public
