stages:
  - setup_tests
  - run_tests
  - pages
  - automated-api-tests

setup_and_run_tests:
  stage: setup_tests
  image: mcr.microsoft.com/playwright/python:v1.38.0-jammy
  script:
    - pip install -r requirements.txt
    - cp .env.example .env
    - python test_dotenv.py
    - PLAYWRIGHT_BROWSERS_PATH=/ms-playwright python -m playwright install --with-deps chromium
    - pytest --junitxml=reports/xml/report.xml --template=html1/index.html --report=reports/html/index.html -m ui -v

pages:
  stage: pages
  script:
    - ls
    - ls reports/html
    - mkdir .public
    - cp -r reports/html/* .public
    - mv .public public
  artifacts:
    paths:
      - public
