stages:
  - test
  - pages
  - automated-api-tests

test:
  stage: test
  image: mcr.microsoft.com/playwright/python:v1.38.0-jammy
  script:
    - pip install -r requirements.txt
    - PLAYWRIGHT_BROWSERS_PATH=/ms-playwright python -m playwright install --with-deps chromium
    - pytest --junitxml=reports/xml/report.xml --template=html1/index.html --report=reports/html/index.html --base-url https://demoqa.com
  artifacts:
    paths:
      - reports
pages:
  stage: pages
  script:
    - ls
    - ls reports/html
    - mkdir .public
    - cp -r reports/html/* .public
    - mv .public public
  artifacts:
    paths:
      - public

automated-api-tests:
  stage: automated-api-tests
  image: cimg/base:2021.04
  before_script:
    # Installing Postman CLI
    - curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
  script:
    # Login using your Postman API keys
    - postman login --with-api-key $POSTMAN_API_KEY
    - postman collection run $POSTMAN_COLLECTION_ID -e $POSTMAN_ENVIRONMENT_ID
