stages:
  - setup_tests
  - run_tests
  - pages
  - automated-api-tests

setup_tests:
  stage: setup_tests
  image: mcr.microsoft.com/playwright/python:v1.38.0-jammy
  script:
    - pip install -r requirements.txt
    - cp .env.example .env
    - python test_dotenv.py
    - PLAYWRIGHT_BROWSERS_PATH=/ms-playwright python -m playwright install --with-deps chromium
  artifacts:
    paths:
      - reports

ui:
  stage: run_tests
  image: mcr.microsoft.com/playwright/python:v1.38.0-jammy
  needs: [ "setup_tests" ]
  script:
    - pytest --junitxml=reports/xml/report.xml --template=html1/index.html --report=reports/html/index.html -m ui -v

api:
  stage: run_tests
  image: mcr.microsoft.com/playwright/python:v1.38.0-jammy
  needs: [ "setup_tests" ]
  script:
    - pytest --junitxml=reports/xml/report.xml --template=html1/index.html --report=reports/html/index.html -m api -v


#pages:
#  stage: pages
#  script:
#    - ls
#    - ls reports/html
#    - mkdir .public
#    - cp -r reports/html/* .public
#    - mv .public public
#  artifacts:
#    paths:
#      - public
